// Generated by https://quicktype.io

export interface Planifier {
    datedebut:    string;
    datefin:      string;
    title:        string;
    formationId:  number;
    formateurId:  number;
    entrepriseId: number;
    groupeId:     number;
}
